apiVersion: v1
kind: ConfigMap
metadata:
  name: chat-settings
data:
  settings.yml: |
    database:
      uri: mongodb://{{ .Release.Name }}-mongodb/letschat	 
{{- if .Values.files_support.enabled }}
    files:
      enable: true
      provider: local
      maxFileSize: 100000000
      restrictTypes: true
      allowedTypes:
{{- if .Values.files_support.allow.images }}
        - 'image/jpeg'
        - 'image/png'
        - 'image/gif'
{{- end }}
{{- if .Values.files_support.allow.documents }}
        - 'application/msword'
        - 'application/msword'
        - 'application/vnd.openxmlformats-officedocument.wordprocessingml.document'
        - 'application/vnd.ms-excel'
        - 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet'
        - 'application/vnd.ms-powerpoint'
        - 'application/vnd.openxmlformats-officedocument.presentationml.presentation'
        - 'text/csv'
        - 'text/plain'
{{- end }}
      local:
        dir: uploads
{{- end }}