apiVersion: v1
kind: PersistentVolume
metadata:
  name: lets-chat-pv
spec:
  storageClassName: manual
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/tmp/data"
