apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}-app
  labels:
    app: {{ .Chart.Name }}
    tier: frontend
spec:
  type: NodePort
  ports:
  - port: 8080
    nodePort: 30303
  selector:
    app: {{ .Chart.Name }}
    tier: frontend

